/*
 * Builds the two files Obsidian loads: main.js and styles.css.
 *
 *   node build.mjs              watch, for development
 *   node build.mjs production   one minified build, then exit
 *
 * Output goes to the repository root, because that is where Obsidian's release
 * assets are read from. Point FATHOMARK_VAULT at a scratch vault to build
 * straight into it instead:
 *
 *   FATHOMARK_VAULT=~/vaults/scratch pnpm dev
 *
 * manifest.json is copied alongside in that case, so the folder is a loadable
 * plugin. Pair it with the `hot-reload` plugin to skip the manual reload.
 */
import { spawn } from "node:child_process";
import { copyFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import builtins from "builtin-modules";
import esbuild from "esbuild";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");
const production = process.argv[2] === "production";

const vault = process.env.FATHOMARK_VAULT;
const outDir = vault
  ? join(resolve(vault.replace(/^~/, process.env.HOME ?? "~")), ".obsidian", "plugins", "fathomark")
  : repoRoot;

if (outDir !== repoRoot) {
  mkdirSync(outDir, { recursive: true });
  copyFileSync(join(repoRoot, "manifest.json"), join(outDir, "manifest.json"));
}

const banner = `/*
Fathomark — this file is generated by esbuild.
Read the source at https://github.com/sunub/fathomark
*/
`;

/*
 * Obsidian ships these at runtime. Bundling them produces a second, unrelated
 * copy of CodeMirror and breaks the editor. React is NOT in this list — the
 * plugin brings its own.
 */
const external = [
  "obsidian",
  "electron",
  "@codemirror/autocomplete",
  "@codemirror/collab",
  "@codemirror/commands",
  "@codemirror/language",
  "@codemirror/lint",
  "@codemirror/search",
  "@codemirror/state",
  "@codemirror/view",
  "@lezer/common",
  "@lezer/highlight",
  "@lezer/lr",
  ...builtins,
];

const context = await esbuild.context({
  entryPoints: [join(here, "src/main.ts")],
  outfile: join(outDir, "main.js"),
  bundle: true,
  format: "cjs",
  platform: "browser",
  target: "es2021",
  external,
  sourcemap: production ? false : "inline",
  minify: production,
  treeShaking: true,
  logLevel: "info",
  banner: { js: banner },
  jsx: "automatic",
  define: { "process.env.NODE_ENV": production ? '"production"' : '"development"' },
  metafile: production,
  /*
   * design-system is consumed as source from a sibling workspace package, so
   * Node resolution would find its own react before ours. Two React copies in
   * one bundle means "invalid hook call" at runtime, and it fails late and
   * confusingly — so pin both to this package's copy explicitly.
   */
  alias: {
    react: resolve(here, "node_modules/react"),
    "react-dom": resolve(here, "node_modules/react-dom"),
  },
});

const css = spawn(
  "pnpm",
  [
    "exec",
    "tailwindcss",
    "--input",
    join(here, "src/styles/plugin.css"),
    "--output",
    join(outDir, "styles.css"),
    ...(production ? ["--minify"] : ["--watch"]),
  ],
  { cwd: here, stdio: "inherit" },
);
css.on("exit", (code) => {
  if (production && code !== 0) process.exit(code ?? 1);
});

if (production) {
  const result = await context.rebuild();
  await context.dispose();

  // `bytes` is the output file's size; `bytesInOutput` is per contributing input.
  const bytes = Object.values(result.metafile.outputs).reduce((sum, out) => sum + out.bytes, 0);
  console.log(`main.js ${(bytes / 1024).toFixed(0)} KB minified`);

  /*
   * ARCHITECTURE.md requires startup to stay cheap, and every kilobyte here is
   * parsed before the workspace is ready. This is not a hard limit yet — it is a
   * tripwire, so that adding a dependency is a decision rather than a drift.
   */
  const budgetKb = 900;
  if (bytes / 1024 > budgetKb) {
    console.error(
      `main.js exceeds the ${budgetKb} KB budget. Raise it deliberately or trim a dependency.`,
    );
    process.exit(1);
  }
} else {
  await context.watch();
  console.log(`watching — output in ${outDir}`);
}
